### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Apathialol** [pelaxa/MMM-ImmichSlideShow#1]
There's no garbage collection for the array of images:
![image](https://github.com/pelaxa/MMM-ImmichSlideShow/assets/8907839/046586ec-8c93-4f53-aebb-5b15cf927bdd)
This results in high memory usage when running even after 10 minutes:
![image](https://github.com/pelaxa/MMM-ImmichSlideShow/assets/8907839/ad432a75-896e-4565-9a00-c6c23062a8b4)

**Comment by pelaxa** [comment]
Thanks for reporting this and sorry for delay.  Looks like this is related to the debug logging i was doing.  Fix coming soon
