### ISSUE TITLE
Notifications not working.

### ISSUE THREAD

**Issue by Snille** [pelaxa/MMM-ImmichSlideShow#10]
Hi again, I'm trying to send notifications to the module to change the picture (both next and previous), but I can't get it to work.
I have the MMM-Remote-Control module enabled (other commands work)
This is what I've tried:
From ssh: 
Sent: `curl -X GET "http://10.0.0.186:8080/api/notification/IMMICHSLIDESHOW_NEXT" -H "accept: application/json" -H "Authorization: Bearer tHeSeCrEtKey"`
Response: `{"success":true,"notification":"IMMICHSLIDESHOW_NEXT","payload":{}}`
But no picture change...

Sent:  `curl -X GET "http://10.0.0.186:8080/api/notification/IMMICHSLIDESHOW_NEXT/IMMICHSLIDESHOW_NEXT" -H "accept: application/json" -H "Authorization: Bearer tHeSeCrEtKey"`
Response: `{"success":true,"notification":"IMMICHSLIDESHOW_NEXT","payload":"IMMICHSLIDESHOW_NEXT"}`
But no picture change...

Also tried from the API (documentation): `http://10.0.0.186:8080/api/docs`
![image](https://github.com/pelaxa/MMM-ImmichSlideShow/assets/1011699/bfae9e77-0ec6-471e-8b01-fe3861744040)
and with both fields populated:
![image](https://github.com/pelaxa/MMM-ImmichSlideShow/assets/1011699/31e5183d-6480-4df4-b0ed-43e0bc491ffe)

My module config:
```
		{
			disabled: false,
			module: 'MMM-ImmichSlideShow',
			position: "fullscreen_below",
			classes: "Photos",
			config: {
				apiKey: 'ThEvErYSeCrEtKeY',
				immichUrl: 'The.IP.to.immichserver',
				slideshowSpeed: 5*60*1000,
				mode: 'album',
				albumName: 'Fotoram Stor',
				sortImagesBy: 'random',
				showImageInfo: true,
				imageInfoLocation: 'bottomRight',
				imageInfo: [ 'date', 'people', 'geo'],
				showProgressBar: true,
				backgroundSize: 'contain',
				transitions: ['opacity'],
				transitionSpeed: '3s',
				transitionImages: true,
				changeImageOnResume: false
			}
		}
```

What am I missing? :)

Ps: Also noticed that if I hide and show (or only send "show module" even when it's already showing) the module it changes the picture to the next one even if I have the "changeImageOnResume: false" set.

**Comment by pelaxa** [comment]
:) Glad someone is trying the various features.

This was just copied over from MMM-Backgroundslideshow but I never use it or test it.  I'll see if it is an easy fix.

**Comment by Snille** [comment]
Hi! Yes, it's "kind of" easy, I actually forked you module to do some testing... :) The problem is that the "notifications" coming from other modules are not "socketnotifications", just "notifications"... :)
Anyway, I'll keep testing on my fork a bit, see if I can figure out some other stuff as well.. :)

**Comment by pelaxa** [comment]
This is fixed now, but no matter what I tried I could not get it to properly register with MMM-Remote-Control.  it just does not show the actions. 

The only supported notifications are:
- IMMICHSLIDESHOW_PAUSE
- IMMICHSLIDESHOW_RESUME
- IMMICHSLIDESHOW_NEXT
- IMMICHSLIDESHOW_PREVIOUS

**Comment by Snille** [comment]
Thank you! All good, it works now from Home Assistant to change pictures back and forth!
