### ISSUE TITLE
Chatty in the logs... :)

### ISSUE THREAD

**Issue by Snille** [pelaxa/MMM-ImmichSlideShow#11]
Hi again, this is not really an issue, more a feature request. :)
The module is quite chatty and I'm thinking it would be good to have an option to set to only log real essential stuff or for example "errors"... Or even not log anything... :)

I'm using the module in multiple "Digital Photo Frame":s on a Raspberry Pi:s and I'm really trying to make the logging as minimal as possible to make the SD-Card last longer and not fill up.... 

Anyway, thank you for fixing the other things! :)

**Comment by pelaxa** [comment]
it sure is chatty!  waiting to get it more stable before I comment out most of the logging, but that should be easy to do on your own if you like for now.

I'll see how easy it is to set the log level from the module config so most folks can have it off.

**Comment by Snille** [comment]
Ok, no problem. :)
I did not know you could turn off logging, how do I do that? Can I set it to off for each module?
And without doing any changes to the module itself? I want to keep in line with your module development of course... :) It's been a while since I wrote my modules.... :)

Thank you!
