### ISSUE TITLE
Lost the "people" information...

### ISSUE THREAD

**Issue by Snille** [pelaxa/MMM-ImmichSlideShow#12]
Hi again, it looks like I've lost the "people" tags in the module?
Does yours still show? I don't believe I changed anything except for the "backgroundSize" from "cover" to "contain".
I know the people showed up before because I was bragging to my wife about it... :)

Here is my conf:
```javascript
		{
			disabled: false,
			module: 'MMM-ImmichSlideShow',
			hiddenOnStartup: false,
			position: "fullscreen_below",
			classes: "default Photos",
			config: {
				apiKey: 'ThEVeRySeCrETaPiKey',
				immichUrl: 'https://SeCret.net',
				slideshowSpeed: 5*60*1000,
				mode: 'album',
				albumName: 'Fotoram Stor',
				sortImagesBy: 'random',
				showImageInfo: true,
				imageInfoLocation: 'bottomRight',
				imageInfo: [ 'date', 'people', 'geo'],
				showProgressBar: true,
				backgroundSize: 'contain',
				transitions: ['opacity'],
				transitionSpeed: '3s',
				transitionImages: true,
				changeImageOnResume: false,
				infologging: false
			}
		},
```

Anything I'm missing?

**Comment by pelaxa** [comment]
I see what is happening here!  the Immich API keeps changing.  For a while I could not get exifInfo unless I made an extra call for each photo and now it looks like the people info is not coming back without that extra call.

this is an easy fix, but it'll have to wait till tonight maybe.

**Comment by Snille** [comment]
Ah, I see... Then it's not me. :) No stress.
Thank you!
