### ISSUE TITLE
Age

### ISSUE THREAD

**Issue by jaud7of8** [pelaxa/MMM-ImmichSlideShow#13]
Hello,
your module is simply amazing!  Not only does it use a popular self hosted picture service, it will pull pictures based on the date to avoid having stale images, and will list the names, since and location (and file name)!!!
This is incredible, any you have my most appreciative thanks.

I wondered if it would be possible to also list the ages of the people in the picture as immich will do?
I looked at the source code and found lines in MMM-ImmichSlideShow.js like

//validate imageinfo property.  This will make sure we have at least 1 valid value
    const imageInfoRegex = /\bname\b|\bdate\b|\bsince\b|\bgeo\b|\bpeople\b/gi;

and

 case 'people': // show people in image
          // Only display last path component as image name if recurseSubDirectories is not set.
          if (Array.isArray(imageinfo.people)) {
            let peopleName = '';
            imageinfo.people.forEach(people => {
              if (peopleName.length > 0) {
                peopleName += ', ';
              }
              peopleName += people.name || '';
            })
            // Remove file extension from image name.
            if (peopleName.length > 0) {
              imageProps.push(peopleName);
            }
          }
that mention people, date, since...
Unfortunately, my knowledge of js and api's is not up to the task of adding this function.
If this is something you would consider doing, or letting me know where to start looking to add the function I am looking for, I would appreciate it.
Thanks

**Comment by pelaxa** [comment]
Hi!
I have not seen this feature in Immich.  Let me check it out and see if this is feasible or not and how much work it would be.

**Comment by pelaxa** [comment]
Closed in v0.8.0

**Comment by jaud7of8** [comment]
Pelaxa, thank you for adding this feature!
