### ISSUE TITLE
API changes...

### ISSUE THREAD

**Issue by Snille** [pelaxa/MMM-ImmichSlideShow#14]
Hi there, updated the Immich server to [v1.106.3](https://github.com/immich-app/immich/releases)
They did changes to the API... :) I now get:
```
0|MagicMirror  | [2024-06-12 22:57:24.536] [ERROR] MMM-ImmichSlideShow :: node_helper :: Oops!  Exception while fetching albums from Immich Request failed with status code 404
0|MagicMirror  | [2024-06-12 22:57:24.536] [ERROR] MMM-ImmichSlideShow :: node_helper :: could not find the specified album in Immich.  Please check your configuration again
```
flooding the log... :)

Have you see this?

**Comment by etymotic** [comment]
Here is where the API changes are mentioned in the release notes https://github.com/immich-app/immich/releases/tag/v1.106.1
