### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'slideshowSpeed')

### ISSUE THREAD

**Issue by pavirtual83** [pelaxa/MMM-ImmichSlideShow#16]
Just added this module to my MM but can't seem to get it to work.  I get no pictures and noted this in the error log.  Any ideas?  I'm running MM server and Immich in a docker environment.

[2024-06-18 22:02:14.388] [ERROR] Whoops! There was an uncaught exception... 
[2024-06-18 22:02:14.396] [ERROR] TypeError: Cannot read properties of undefined (reading 'slideshowSpeed')
    at Class.resume (/opt/magic_mirror/modules/MMM-ImmichSlideShow/node_helper.js:474:57)
    at Class.socketNotificationReceived (/opt/magic_mirror/modules/MMM-ImmichSlideShow/node_helper.js:522:12)
    at Socket.<anonymous> (/opt/magic_mirror/js/node_helper.js:98:11)
    at Socket.emit (node:events:519:28)
    at Socket.emitUntyped (/opt/magic_mirror/node_modules/socket.io/dist/typed-events.js:69:22)
    at /opt/magic_mirror/node_modules/socket.io/dist/socket.js:704:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) 
[2024-06-18 22:02:14.396] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection? 
[2024-06-18 22:02:14.397] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MagicMirrorOrg/MagicMirror/issues 
[2024-06-18 22:04:17.675] [ERROR] Whoops! There was an uncaught exception... 
[2024-06-18 22:04:17.675] [ERROR] TypeError: Cannot read properties of undefined (reading 'slideshowSpeed')
    at Class.resume (/opt/magic_mirror/modules/MMM-ImmichSlideShow/node_helper.js:474:57)
    at Class.socketNotificationReceived (/opt/magic_mirror/modules/MMM-ImmichSlideShow/node_helper.js:522:12)
    at Socket.<anonymous> (/opt/magic_mirror/js/node_helper.js:98:11)
    at Socket.emit (node:events:519:28)
    at Socket.emitUntyped (/opt/magic_mirror/node_modules/socket.io/dist/typed-events.js:69:22)
    at /opt/magic_mirror/node_modules/socket.io/dist/socket.js:704:39
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) 
[2024-06-18 22:04:17.676] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?

**Comment by pelaxa** [comment]
Without revealing your access token and perhaps immich url, can you post your config for this module?

**Comment by pavirtual83** [comment]
let config = {
	address: "0.0.0.0",	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/",	// The URL path where MagicMirror² is hosted. If you are using a Reverse proxy
									// you must set the sub path here. basePath must end with a /
	ipWhitelist: [],	// Set [] to allow all IP addresses
									// or add a specific IPv4 of 192.168.1.5 :
									// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
									// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
									// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false,			// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "",	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "",	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	locale: "en-US",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 12,
	units: "imperial",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Family Calendar",
//			position: "top_left",
			config: {
				broadcastPastEvents: true,
				calendars: [
					{
//						fetchInterval: 7 * 24 * 60 * 60 * 1000,
						symbol: "calendar-check",
						url: "myothercal.ics",
						name: "pd_shared",
						color: 'blue'
					},

					{
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics",
						name: "us_holiday", // <-- specify calendar name
						color: "green", // <-- if you don't want to get color, just remove this line.
						broadcastPastEvents: true, // <-- need to broadcast past events
						maximalNumberOfDays: 30, // <-- how old events would be broadcasted
						maximumEntries: 100, // <-- assign enough number to prevent truncating new events by old events.
					  },

					{
//						fetchInterval: 7 * 24 * 60 * 60 * 1000,
						symbol: "calendar-check",
						url: "my.ics",
						name: "pd_call",
						color: 'red'
					}
				]
			}
		},
//		{
//			module: "compliments",
//			position: "lower_third"
//		},
		{
			module: "weather",
			position: "top_right",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				location: "mylocation",
				locationID: "mylocationID", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "myapikey"
			}
		},
		{
			module: "weather",
			position: "top_right",
			header: "Weather Forecast",
			colored: true,
			config: {
				weatherProvider: "openweathermap",
				type: "forecast",
				location: "mylocatione",
				locationID: "mylocationID", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "myapikey"
			}
		},

	{
		module: "MMM-CalendarExt3",
		position: "fullscreen_above",
		title: "Patel Family Calendar",
		classes: "MMM-CalendarExt3-month",
		config: {
	  	mode: "month",
	  	instanceId: "monthlyCalendar",
//	  	locale: 'de-DE',
	  	maxEventLines: 5,
	  	firstDayOfWeek: 1,
	  	calendarSet: ['us_holiday', 'pd_shared', 'pd_call'],
	}
  },

  {
	module: "MMM-CalendarExt3Agenda",
	position: "top_left",
	header: "My Agenda", 
	config: {
	  instanceId: "agendaCalendar",
	  firstDayOfWeek: 1,
	  startDayIndex: -1,
		  endDayIndex: 10,
	  calendarSet: ['us_holiday', 'pd_shared', 'pd_call'],
	}
  },



  {
	module: 'MMM-pages',
	config: {
			modules:
				[[ "clock", "weather", "MMM-CalendarExt3Agenda", "MMM-ImmichSlideShow"],
				 [ "MMM-CalendarExt3-month" ]],
			fixed: [ "alert", "updatenotification"],
			rotationTime: 60000

	}
},


{
    module: 'MMM-ImmichSlideShow',
    position: 'middle_center',
    config: {
	  apiKey: 'myapikey',
	  immichUrl: 'http://192.myinternalipaddress:2283',
//	  immichUrl: 'https://photos.mydomain.xyz',	
	  mode: 'album',
//	  albumId: '0g7dhFF-M2XzDmzfaJAP0o6lCCw8Hja89IK4W4FdvbpsNK0tZ32zsw1lOmXmTylQeQc',
	  albumName: 'MM',
      numDaysToInclude: 700,
      transitionImages: true
    }
  }
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") { module.exports = config; }

**Comment by pavirtual83** [comment]
let config = {

	address: "0.0.0.0",	// Address to listen on, can be:
							// - "localhost", "127.0.0.1", "::1" to listen on loopback interface
							// - another specific IPv4/6 to listen on a specific interface
							// - "0.0.0.0", "::" to listen on any interface
							// Default, when address config is left out or empty, is "localhost"
	port: 8080,
	basePath: "/",	// The URL path where MagicMirror² is hosted. If you are using a Reverse proxy
									// you must set the sub path here. basePath must end with a /
	ipWhitelist: [],	// Set [] to allow all IP addresses
									// or add a specific IPv4 of 192.168.1.5 :
									// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
									// or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
									// ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

	useHttps: false,			// Support HTTPS or not, default "false" will use HTTP
	httpsPrivateKey: "",	// HTTPS private key path, only require when useHttps is true
	httpsCertificate: "",	// HTTPS Certificate path, only require when useHttps is true

	language: "en",
	locale: "en-US",
	logLevel: ["INFO", "LOG", "WARN", "ERROR"], // Add "DEBUG" for even more logging
	timeFormat: 12,
	units: "imperial",

	modules: [
		{
			module: "alert",
		},
		{
			module: "updatenotification",
			position: "top_bar"
		},
		{
			module: "clock",
			position: "top_left"
		},
		{
			module: "calendar",
			header: "Family Calendar",
//			position: "top_left",
			config: {
				broadcastPastEvents: true,
				calendars: [
					{
//						fetchInterval: 7 * 24 * 60 * 60 * 1000,
						symbol: "calendar-check",
						url: "linktobasic.ics",
						name: "pd_shared",
						color: 'blue'
					},

					{
						url: "webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics",
						name: "us_holiday", // <-- specify calendar name
						color: "green", // <-- if you don't want to get color, just remove this line.
						broadcastPastEvents: true, // <-- need to broadcast past events
						maximalNumberOfDays: 30, // <-- how old events would be broadcasted
						maximumEntries: 100, // <-- assign enough number to prevent truncating new events by old events.
					  },

					{
//						fetchInterval: 7 * 24 * 60 * 60 * 1000,
						symbol: "calendar-check",
						url: "pdcalllink.ics",
						name: "pd_call",
						color: 'red'
					}
				]
			}
		},
//		{
//			module: "compliments",
//			position: "lower_third"
//		},
		{
			module: "weather",
			position: "top_right",
			config: {
				weatherProvider: "openweathermap",
				type: "current",
				location: "mylocation",
				locationID: "mylocationid", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "myapikey"			}
		},
		{
			module: "weather",
			position: "top_right",
			header: "Weather Forecast",
			colored: true,
			config: {
				weatherProvider: "openweathermap",
				type: "forecast",
				location: "mylocation",
				locationID: "mylocationid", //ID from http://bulk.openweathermap.org/sample/city.list.json.gz; unzip the gz file and find your city
				apiKey: "myapikey"
			}
		},
//		{
//			module: "newsfeed",
//			position: "bottom_bar",
//			config: {
//				feeds: [
//					{
//						title: "New York Times",
//						url: "https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml"
//					}
//				],
//				showSourceTitle: true,
//				showPublishDate: true,
//				broadcastNewsFeeds: true,
//				broadcastNewsUpdates: true
//			}
//		},
	{
		module: "MMM-CalendarExt3",
		position: "fullscreen_above",
		title: "Patel Family Calendar",
		classes: "MMM-CalendarExt3-month",
		config: {
	  	mode: "month",
	  	instanceId: "monthlyCalendar",
//	  	locale: 'de-DE',
	  	maxEventLines: 5,
	  	firstDayOfWeek: 1,
	  	calendarSet: ['us_holiday', 'pd_shared', 'pd_call'],
	}
  },

  {
	module: "MMM-CalendarExt3Agenda",
	position: "top_left",
	header: "My Agenda", 
	config: {
	  instanceId: "agendaCalendar",
	  firstDayOfWeek: 1,
	  startDayIndex: -1,
		  endDayIndex: 10,
	  calendarSet: ['us_holiday', 'pd_shared', 'pd_call'],
	}
  },



  {
	module: 'MMM-pages',
	config: {
			modules:
				[[ "clock", "weather", "MMM-CalendarExt3Agenda", "MMM-ImmichSlideShow"],
				 [ "MMM-CalendarExt3-month" ]],
			fixed: [ "alert", "updatenotification"],
			rotationTime: 60000

	}
},


{
    module: 'MMM-ImmichSlideShow',
    position: 'middle_center',
    config: {
	  apiKey: 'myapikey',
	  immichUrl: 'http://192.myserverip:2283',
	  mode: 'album',
//	  albumId: '0g7dhFF-M2XzDmzfaJAP0o6lCCw8Hja89IK4W4FdvbpsNK0tZ32zsw1lOmXmTylQeQc',
	  albumName: 'MM',
      numDaysToInclude: 700,
      transitionImages: true
    }
  }
	]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") { module.exports = config; }

**Comment by pavirtual83** [comment]
I actually went ahead and deleted my MM container and reinstalled everything and now it all works!! Appreciate your help none the less.  This is an awesome module that you've created.  Thank you!
