### ISSUE TITLE
Next & Previous stopped working?

### ISSUE THREAD

**Issue by Snille** [pelaxa/MMM-ImmichSlideShow#17]
Hi, are your next & previous notification(s) working?
Not sure when they stopped working but the do not work now for me...

MM Version: 2.28.0
Node Version: 20.15.0

My conf:
 ```javascript
	    {
			disabled: false,
			module: 'MMM-ImmichSlideShow',
			hiddenOnStartup: false,
			position: "fullscreen_below",
			//position: "fullscreen_above",
			classes: "default Photos",
			config: {
				apiKey: 'secret-stuff!',
				immichUrl: 'https://to-my-working-immich.com',
				slideshowSpeed: 5*60*1000,
				mode: 'album',
				albumName: 'Fotoram Stor',
				sortImagesBy: "taken",
				showImageInfo: true,
				imageInfoLocation: 'bottomRight',
				imageInfo: [ 'date', 'people', 'age', 'geo'],
				showProgressBar: false,
				backgroundSize: 'contain',
				transitions: ['slideFromBottom'],
				transitionSpeed: '3s',
				transitionImages: false,
				changeImageOnResume: true,
				infologging: false
			}
		},
```

Sending notifocations from HA with NodeRed:
![image](https://github.com/pelaxa/MMM-ImmichSlideShow/assets/1011699/0fcb47b5-7b42-460f-8aed-fcec5d4ae43a)
Notification: IMMICHSLIDESHOW_NEXT or IMMICHSLIDESHOW_PREVIOUS
The msg.{action} is set in the "template" node with the notification...
URL: http://IP-to-Mirror:8080/api/notification/{{action}}

The flow:
![image](https://github.com/pelaxa/MMM-ImmichSlideShow/assets/1011699/24025430-476b-413c-8847-a0e87322c789)

Response Next: {"success":true,"notification":"IMMICHSLIDESHOW_NEXT","payload":{}}
Response Previous: {"success":true,"notification":"IMMICHSLIDESHOW_PREVIOUS","payload":{}}

All looks good... But nothing happens.
Other requests (notifications) to other modules work...
I'm pretty sure this has worked before... I have a "button" to go back and forth among the pictures on my two frames. :)

Can you reproduce? 
Is it working for you?

**Comment by pelaxa** [comment]
that is odd!  You are getting the success message but nothing happens?

what I noticed is that your authorization header value is different than what I have:
```
{"Authorization": "Bearer xxxxxxxxxxx"}
```

But I would expect you not to get success back if that was the issue.  I just tried this on my MagicMirror and I can see the pictures moving back and forth.

```
curl --location 'https://<mm2 FQDN>/api/notification/IMMICHSLIDESHOW_NEXT' \
--header 'Authorization: Bearer <API KEY>' \
--header 'Accept: application/json'
```

**Comment by Snille** [comment]
Found the problem (at least), not fixed it yet... :)
I recently "removed" the "showProgressBar" (showProgressBar: false)... Because it used 60% CPU on the machine (don't know why)... When that is set to false, I get this in the browser console:
```javascript
MMM-ImmichSlideShow.js:628 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'style')
    at Class.suspend (MMM-ImmichSlideShow.js:628:12)
    at Class.notificationReceived (MMM-ImmichSlideShow.js:285:12)
    at sendNotification (main.js:99:12)
    at Object.sendNotification (main.js:650:4)
    at Class.sendNotification (module.js:341:6)
    at Class.socketNotificationReceived (MMM-Remote-Control.js:161:18)
    at module.js:231:9
    at Socket.<anonymous> (socketclient.js:32:4)
    at Emitter.emit (index.mjs:136:20)
    at Socket.emitEvent (socket.js:538:20)
```
It's trying to do something with the progress bar that's not there....
I do like the progress bar, but I could not "afford" the CPU-Power... :)

**Comment by pelaxa** [comment]
Ok.  I’ll take a look at this. Thanks.

**Comment by pelaxa** [comment]
This should be fixed now.

**Comment by Snille** [comment]
Thank you! It's working now. :)
