### ISSUE TITLE
Config question

### ISSUE THREAD

**Issue by etymotic** [pelaxa/MMM-ImmichSlideShow#19]
Hello,

Should I be adding config variables to config.js (MagicMirror config file) or MMM-ImmichSlideShow.js in the MMM-ImmichSlideShow folder?

I see a default config in the MMM-ImmichSlideShow.js. Do these get overridden by config.js?

Thanks!

**Comment by pelaxa** [comment]
yes.  what you see there are the default values and you override what you need in MM2 config.js
