### ISSUE TITLE
Fill background...

### ISSUE THREAD

**Issue by Snille** [pelaxa/MMM-ImmichSlideShow#9]
Hi! I've just moved over to Immich from GooglePhotos and was overjoyed to see that there is a module for Immich as well! :) Thank you!

I have a question/request, when a picture is displayed and you are using backgroundSize: 'contain', is there a way to "fill" the rest of the screen with black (or as in the MMM-GooglePhotos module with a dimmed zoomed in part of current picture)?

Why? My mirror is used as a Digital-Photo-Frame when no one is standing in front of it, so the module is shown "in front of" all the other modules then. But when someone comes in proximity to the mirror, the "picture-module" is hidden and all the other modules are shown...

Again thank you for this module! :)

**Comment by pelaxa** [comment]
I'll see what can be done here.  should not be too difficult hopefully to put a black background.

**Comment by Snille** [comment]
Thank you for fixing this! :)
